### ISSUE TITLE
Robot Controller Configuration

### ISSUE THREAD

**Issue by wolfv** [tork-a/melfa_robot#19]
Hi, 

I was trying to use your package on a Mitsubishi Robot. 

Can you specify how the Robot Controller has to be configured to work properly with the driver?
Does the controller need to run a specific MELFA program prior to communication? Do I need to enable the data link communication?

I think it would be awesome to add some guidance on this in the README: NETIP, NETPORT. CPRCE13, COMDEV, NETMODE, NETHSTIP ... configuration.

Thanks a lot!

**Comment by 7675t** [comment]
Hi @wolfv , thanks for your feedback. I added some instructions in README.md by #21 .
Please check the README.md on the append_readme branch.

You need a small program on the controller side to enable real-time external input, as the README.md says.

If you use RT Toolbox3 simulator, I believe all configuration can stay default. Actually I just used the setup wizard and modified nothing.

When you use the robot controller and actual robot, I think the IP address of the controller is the only information you need to bring up the ROS node. I checked it works fine with CR750-Q and RV-7FL using moveit, but **Please be careful** to use this package with the actual robot. Stay your hand on e-stop button...

If you have any trouble, please share your environment and feel free to ask here. Thanks.

**Comment by wolfv** [comment]
Hi @7675t 

thanks a lot for the detailed explanation. I'll try it right away!

By the way, I am currently working on this with Rapyuta Robotics, and the Rapyuta headquarters are very close to yours in Tokyo. Would you be interested to meet for a coffee? We have a CR800 and RV-4FRL.
Are you interested in contributions for this robot? (e.g. mesh + URDF/xacro files).

Thanks again,

Wolf

**Comment by 7675t** [comment]
@wolfv great, I will contact your gmail address.

**Comment by 7675t** [comment]
I close this issue, #21 will help.
