### ISSUE TITLE
melfa_driver

### ISSUE THREAD

**Issue by KazukiHiraizumi** [tork-a/melfa_robot#28]
お世話になります。
実ロボット(RV4F)で接続トライ中です。
WARN "Failed to receive packet"が出続けますが、ロボット側で設定を変更する箇所はあるでしょうか？

**Comment by y-yosuke** [comment]
状況が同じかどうか分かりませんが，または既にチェック済みかもしれませんが，
2018年に実機動作確認を行った時につまづいたなどした点を下にリストアップします．

- Windows PC での Robot 側へのプログラムのコピー
  - "オフライン" から "オンライン" にドラッグ＆ドロップ でコピー
- 通信相手は Windows ではなくてロボットの IP
- ROS のプログラミングで動作させる場合はロボットのキースイッチを AUTOMATIC にする #4 
- プログラム実行時ロボットティーチングペンダント側での設定
  - https://github.com/tork-a/melfa_robot/issues/4#issuecomment-389748177

**Comment by KazukiHiraizumi** [comment]
ありがとうございます。
現在は教示モードで、ジョイント座標だけを読み出したいのですが、そのような使い方はできるでしょうか？

**Comment by y-yosuke** [comment]
melfa_driver はコントローラ「リアルタイム外部制御機能」を使って 
ROS PC との通信を行っています．ROS での通信・制御のためにはコントローラの
キースイッチを AUTOMATIC にしてペンダントで下記プログラムを実行する必要があります．
https://github.com/tork-a/melfa_robot#program-for-real-time-external-control-1

おっしゃっておられる「教示モード」でコントローラのキースイッチを MANUAL にする必要が
あるとすると，上記の通信を行うプログラムを実行できないので ROS 側でモニタすることも
できない状態であると考えられます．

加えて，我々が実機動作確認を行った範囲においても MANUAL モードでの先述の
「リアルタイム外部制御機能」のためのプログラム実行はできず，AUTOMATIC に切替えたら
実行することができたと記憶しています．

**Comment by KazukiHiraizumi** [comment]
[CR750,CR751 - Instruction Manual (Ethernet Function) BFP-A3379-0 (03.15).pdf](https://github.com/tork-a/melfa_robot/files/4335588/CR750.CR751.-.Instruction.Manual.Ethernet.Function.BFP-A3379-0.03.15.pdf)
こちらのドキュメントを見ると、モニターのみのモードもあるようです。
こちらで試してみて、必要あればプルレク送ります。
ありがとうございました
一旦クローズします
