### ISSUE TITLE
実機作動手順 @実機動作確認 2018.05.17

### ISSUE THREAD

**Issue by y-yosuke** [tork-a/melfa_robot#4]
## 実機作動手順

- 電源投入前に安全を見て手先を外してもらった．

1. 壁面ブレーカ ON
1. 台座ブレーカ ON
  全体の電源が入る
1. 3Dセンサスイッチ ON（必要ならば）
  今回は不要なので OFF のまま
1. ティーチング操作
   1. サーボ ON
   1. ティーチモードならば
      1. 台座のキーを MANUAL にする
      1. ENABLEボタン（デッドマンスイッチ）を押しながらティーチングモード動作
   1. プログラミングで動作させるならば
      1. 台座のキースイッチを AUTOMATIC にする

台座にあるブレーカー
![img_0550](https://user-images.githubusercontent.com/3119480/40193718-0e66ee92-5a43-11e8-8bf8-666b7e496e63.JPG)

台座のキースイッチなど全体
![img_0548](https://user-images.githubusercontent.com/3119480/40194037-0d61505e-5a44-11e8-862b-25340d33a3cb.JPG)

台座のキースイッチなど拡大
![img_0549](https://user-images.githubusercontent.com/3119480/40193921-bac8ad2e-5a43-11e8-992b-d742ef8ba369.JPG)

ティーチングペンダント
![img_0551](https://user-images.githubusercontent.com/3119480/40193944-c9b6d3c4-5a43-11e8-9f8c-f806baf8e21b.JPG)

**Comment by ChunJyeBehBeh** [comment]
Sorry for me to speak English. I have translate the webpage and I would like to ask something.

I want to try to control the robotics arm with ROS. So I connect the robotics arm to a router and my Linux ROS PC to the same router also.

However, when I run the program on the pendant, it report the following error.
    - L6130 Network Communication error (1)
May I know how to solve it?

![WhatsApp Image 2019-05-23 at 09 24 48](https://user-images.githubusercontent.com/35726770/58219488-bbdfe380-7d3d-11e9-9e79-549a66b32faa.jpeg)

**Comment by Moirai** [comment]
You can check "Message", "Cause", "Parameter" on your pendant display.

**Comment by ChunJyeBehBeh** [comment]
So I assume that I set up the parameters wrongly. 

I am going to use ROS to control the robotics arm and the screenshot is the setup. There are three parameters under Communication parameter such as RS-232, Ethernet and Real-time external control command. Do I need to setup for RS-232 and Real-time external control command?

![mitsubishi_setup](https://user-images.githubusercontent.com/35726770/58449088-a05d4a00-813c-11e9-9911-149329e94284.jpg)

![WhatsApp Image 2019-05-28 at 11 38 46](https://user-images.githubusercontent.com/35726770/58449230-35f8d980-813d-11e9-85aa-8de018907251.jpeg)

Is my network parameters setup correctly? I am not sure for the device list and device allocation under the Ethernet parameter also.

My pendant version is R56TB and controller is CR750-D. Thanks for the help.

**Comment by Moirai** [comment]
Instruction Manual is here.
[R56TB_Instruction_Manual.pdf](https://github.com/tork-a/melfa_robot/files/3225711/R56TB_Instruction_Manual.pdf)

**Comment by 7675t** [comment]
Hi, I believe you don't have to set any value in Device list: and Device allocation: sections. You only have to set IP address, subnet and gateway. I recommend you to reset all setting as factory setting and try it again. Good luck.
